name: Build and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Gulp build
      - name: Run Gulp Build
        run: gulp build

      # Step 5: Preprocess Build Output
      - name: Preprocess Build Output
        run: |
          # Remove symbolic links (if any)
          find output/ -type l -delete
          # Display size for debugging
          du -sh output/

      # Step 6: Verify Required Files
      - name: Ensure index.html Exists
        run: |
          if [ ! -f output/index.html ]; then
            echo "Error: index.html not found in output/"
            exit 1
          fi

      # Step 7: Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Must match deploy step expectation
          path: output/       # Ensure this matches your build output directory
          # Uncomment to include hidden files if needed
          # include-hidden-files: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # Step 1: Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Must match artifact uploaded in build step
          path: output/

      # Step 2: Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
